### ISSUE TITLE
Write the README.md

### ISSUE THREAD

**Issue by omar-abdelgawad** [omar-abdelgawad/image2image#18]
Currently, our README.md has only the title and some badges. We want to fill it with some information about the models we are implmenting such as Pix2Pix, UNIT, and TUNIT. I am thinkting that the structure of the README should be like pytorch-gan repository.
https://github.com/eriklindernoren/PyTorch-GAN

Please provide a good structure first such as the table of contents and outline. Everything can be filled in as we march through our goals.

**Comment by JoshLamptey** [comment]
hi can i be assigned this please

**Comment by JoshLamptey** [comment]
i have already started working on it. 
i have started with the structure and i have written the the documentation for Pix2Pix and UNIT . i will write the documentation for TUNIT and make a pr when i close from work tonight

**Comment by omar-abdelgawad** [comment]
I apologize for any confusion, but this repository is designated for a university class project and will be evaluated for grading purposes. Regrettably, we are unable to accept assistance from individuals outside our designated team of 10 collaborators. Additionally, we will not be considering any pull requests from individuals who are not part of the same 10-member team. We appreciate your efforts and apologize for any misunderstanding this may have caused.
